services:
  - type: web
    name: flashspeak
    runtime: docker
    plan: starter
    dockerfilePath: ./app.dockerfile
    dockerContext: .
    healthCheckPath: /
    region: singapore
    domains: 
      - flashspeak.online
    # repo: https://github.com/lukerohde/our-meals
    branch: main
    numInstances: 1
    # scaling: # Autoscaling configuration (not available for hobby plans)
    #   minInstances: 1
    #   maxInstances: 3
    #   targetMemoryPercent: 60 # Optional if targetCPUPercent is set
    #   targetCPUPercent: 60    # Optional if targetMemory is set
    envVars:
      - key: PORT
        value: "3000"
      - key: DJANGO_DEBUG
        value: "0"
      - key: DJANGO_ALLOWED_HOSTS
        value: www.flashspeak.online,flashspeak.online,flashspeak.onrender.com
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@flashspeak.online
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: flashspeak-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
databases:
  - name: flashspeak-db
    region: singapore
    postgresMajorVersion: "15"
    databaseName: flashspeak
    plan: free
    ipAllowList: [] # only allow internal connections
