# Generated by Django 5.1.4 on 2025-02-14 03:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_application_delete_thing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.JSONField(default=list)),
                ('front_last_review', models.DateTimeField(blank=True, null=True)),
                ('front_interval', models.IntegerField(default=1)),
                ('front_review_count', models.IntegerField(default=0)),
                ('front_easiness_factor', models.FloatField(default=2.5)),
                ('front_repetitions', models.IntegerField(default=0)),
                ('back_last_review', models.DateTimeField(blank=True, null=True)),
                ('back_interval', models.IntegerField(default=1)),
                ('back_review_count', models.IntegerField(default=0)),
                ('back_easiness_factor', models.FloatField(default=2.5)),
                ('back_repetitions', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
