# Generated by Django 5.1.4 on 2025-02-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_flashcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='flashcards', to='main.application'),
        ),
    ]
