# Generated by Django 5.1.4 on 2025-02-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_flashcard_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='backside_notes',
            field=models.TextField(blank=True, help_text='Notes for the back side of the card', null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='frontside_notes',
            field=models.TextField(blank=True, help_text='Notes for the front side of the card', null=True),
        ),
    ]
