# Generated by Django 5.1.4 on 2025-02-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_flashcard_backside_notes_flashcard_frontside_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='backside_notes',
            new_name='back_notes',
        ),
        migrations.RenameField(
            model_name='flashcard',
            old_name='frontside_notes',
            new_name='front_notes',
        ),
    ]
