# Generated by Django 5.1.4 on 2025-02-18 19:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_backside_notes_flashcard_back_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='applications',
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the deck', max_length=255)),
                ('deck_type', models.CharField(choices=[('job_application', 'Job Application'), ('study', 'Study Materials'), ('language', 'Language Learning')], default='study', help_text='Type of deck', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='active', help_text='Status of the deck (e.g., active, archived)', max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='flashcard',
            name='decks',
            field=models.ManyToManyField(blank=True, related_name='flashcards', to='main.deck'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the document', max_length=255)),
                ('url', models.URLField(blank=True, help_text='URL to the document in S3', null=True)),
                ('content', models.TextField(help_text='Extracted or provided text content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='deck',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='decks', to='main.document'),
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the tutor', max_length=255)),
                ('deck_name', models.CharField(help_text='Display name for decks of this type', max_length=255)),
                ('url_path', models.CharField(help_text='URL path for this tutor (e.g. interview-coach)', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='deck',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='main.tutor'),
        ),
        migrations.CreateModel(
            name='TutorPromptOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tutor_url_path', models.CharField(help_text='URL path of the tutor', max_length=255)),
                ('key', models.CharField(help_text='Dotted path to the prompt key', max_length=255)),
                ('value', models.TextField(help_text='Override value for the prompt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tutor_url_path', 'key'],
                'unique_together': {('user', 'tutor_url_path', 'key')},
            },
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
