# Generated by Django 5.1.4 on 2025-02-18 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_flashcard_applications_deck_flashcard_decks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('resume', 'Resume'), ('job_description', 'Job Description'), ('study_material', 'Study Material'), ('language_text', 'Language Text')], default='study_material', help_text='Type of document', max_length=50),
        ),
        migrations.AddField(
            model_name='tutor',
            name='config_path',
            field=models.CharField(blank=True, help_text='Path to the YAML config file', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Whether this is a system tutor loaded from YAML'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Superuser who manages this tutor. Only required for non-system tutors.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to=settings.AUTH_USER_MODEL),
        ),
    ]
