# Generated by Django 5.1.4 on 2025-02-18 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_document_document_type_tutor_config_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='owner',
        ),
    ]
