# Generated by Django 5.1.4 on 2025-02-18 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_tutor_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='is_system',
        ),
    ]
