# Generated by Django 5.1.4 on 2025-02-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_tutor_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='content',
            field=models.TextField(blank=True, help_text='Text content for generating flashcards', null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the deck', null=True),
        ),
    ]
