# Generated by Django 5.1.4 on 2025-02-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_deck_content_deck_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='content_placeholder',
            field=models.CharField(blank=True, help_text='Custom placeholder text for the content field', max_length=255, null=True),
        ),
    ]
