# Generated by Django 5.1.4 on 2025-03-03 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='documents',
        ),
        migrations.AddField(
            model_name='document',
            name='deck',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.deck'),
            preserve_default=False,
        ),
    ]
