# Generated by Django 5.1.4 on 2025-03-18 23:11

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_recharge_enabled', models.BooleanField(default=False)),
                ('auto_recharge_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('monthly_recharge_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_credits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_usage', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_tokens', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='billing.billingprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('recharge', 'Manual Recharge'), ('auto_recharge', 'Automatic Recharge'), ('refund', 'Refund'), ('adjustment', 'Account Adjustment'), ('promotion', 'Promotion')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billing.billingprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
