# Generated by Django 5.1.4 on 2025-03-18 23:25

from django.db import migrations


def create_billing_profiles(apps, schema_editor):
    # Get the historical models
    User = apps.get_model('auth', 'User')
    BillingProfile = apps.get_model('billing', 'BillingProfile')
    
    # Create billing profiles for all existing users who don't have one
    for user in User.objects.all():
        BillingProfile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_billing_profiles, migrations.RunPython.noop),
    ]
