# Generated by Django 5.1.4 on 2025-03-19 02:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_create_billing_profiles_for_existing_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_credits', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Default credits to grant to new users upon signup', max_digits=10)),
            ],
            options={
                'verbose_name': 'Billing Settings',
                'verbose_name_plural': 'Billing Settings',
            },
        ),
    ]
