# Generated by Django 5.1.4 on 2025-03-19 03:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_billingsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingsettings',
            name='signup_credits',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default credits to grant to new users upon signup. Set to zero to disable signup credits.', max_digits=10),
        ),
        migrations.CreateModel(
            name='BillingSettingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=6, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('key',)},
            },
        ),
    ]
