# Generated by Django 5.1.4 on 2025-03-19 03:49

from decimal import Decimal
from django.db import migrations


def seed_token_costs(apps, schema_editor):
    # Get the BillingSettingItem model from the app registry
    BillingSettingItem = apps.get_model('billing', 'BillingSettingItem')
    
    # Define the default token costs
    default_costs = [
        # gpt-4o-mini-realtime-preview
        {
            'key': 'gpt-4o-mini-realtime-preview-input-cost',
            'value': Decimal('0.60'),
            'description': 'Cost per million input tokens for gpt-4o-mini-realtime-preview'
        },
        {
            'key': 'gpt-4o-mini-realtime-preview-input-cached-cost',
            'value': Decimal('0.30'),
            'description': 'Cost per million cached input tokens for gpt-4o-mini-realtime-preview'
        },
        {
            'key': 'gpt-4o-mini-realtime-preview-output-cost',
            'value': Decimal('2.40'),
            'description': 'Cost per million output tokens for gpt-4o-mini-realtime-preview'
        },
        
        # gpt-4o-realtime-preview
        {
            'key': 'gpt-4o-realtime-preview-input-cost',
            'value': Decimal('5.00'),
            'description': 'Cost per million input tokens for gpt-4o-realtime-preview'
        },
        {
            'key': 'gpt-4o-realtime-preview-input-cached-cost',
            'value': Decimal('2.50'),
            'description': 'Cost per million cached input tokens for gpt-4o-realtime-preview'
        },
        {
            'key': 'gpt-4o-realtime-preview-output-cost',
            'value': Decimal('20.00'),
            'description': 'Cost per million output tokens for gpt-4o-realtime-preview'
        },
        
        # gpt-4o-mini
        {
            'key': 'gpt-4o-mini-input-cost',
            'value': Decimal('0.150'),
            'description': 'Cost per million input tokens for gpt-4o-mini'
        },
        {
            'key': 'gpt-4o-mini-input-cached-cost',
            'value': Decimal('0.075'),
            'description': 'Cost per million cached input tokens for gpt-4o-mini'
        },
        {
            'key': 'gpt-4o-mini-output-cost',
            'value': Decimal('0.600'),
            'description': 'Cost per million output tokens for gpt-4o-mini'
        }
    ]
    
    # Create the token cost records
    for cost_data in default_costs:
        BillingSettingItem.objects.get_or_create(
            key=cost_data['key'],
            defaults={
                'value': cost_data['value'],
                'description': cost_data['description']
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_billingsettings_signup_credits_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_token_costs, migrations.RunPython.noop),
    ]
