# Generated by Django 5.1.4 on 2025-03-21 20:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_billingprofile_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsettings',
            name='default_recharge_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Default amount shown in the recharge form. Must be between $5 and $1000, in increments of $5.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
