# Generated by Django 5.1.4 on 2025-03-22 04:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_billingsettings_default_recharge_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsettings',
            name='default_monthly_recharge_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Default monthly recharge limit for new users. Typically 4x the default recharge amount.', max_digits=10),
        ),
    ]
